// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ueisbsvhbqsjetppruwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlaXNic3ZoYnFzamV0cHBydXd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NjQ5MTYsImV4cCI6MjA2NjE0MDkxNn0.lyBf4hLOtVSKYHY_tLMyZW8ducBZI1AuK0T0TaCYr2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});